name: VelioraFTB
version: '${project.version}'
main: id.velioragardens.velioraftb.VelioraFTB
api-version: '1.21'

author: XandMe-HX
website: https://github.com/XandMe-HX/VelioraFTB

description: Configurable Farmer, Tree Feller, and Vein Miner skills.

depend:
  - Vault

commands:
  velioraftb:
    description: Membuka menu VelioraFTB.
    usage: /velioraftb [status|reload]
    aliases:
      - vftb
      - ftbskills
    permission: velioraftb.use

permissions:
  velioraftb.use:
    description: Mengizinkan pemain membuka menu VelioraFTB.
    default: true

  velioraftb.skill.vein:
    description: Mengizinkan penggunaan Vein Miner.
    default: true

  velioraftb.skill.tree:
    description: Mengizinkan penggunaan Tree Feller.
    default: true

  velioraftb.skill.farmer:
    description: Mengizinkan penggunaan Farmer.
    default: true

  velioraftb.admin:
    description: Mengizinkan reload konfigurasi VelioraFTB.
    default: op
