name: VelioraVein
version: '${project.version}'
main: id.velioragardens.velioravein.VelioraVein
api-version: '1.21'

author: XandMe-HX
website: https://github.com/XandMe-HX/VelioraVein

description: Skill-based Vein Miner, Tree Feller, and Farmer plugin.

depend:
  - Vault

commands:
  vgvein:
    description: Open the VelioraVein skill shop.
    usage: /vgvein
    aliases:
      - vein
      - vvein
    permission: velioravein.use

permissions:
  velioravein.use:
    description: Allows players to use /vgvein.
    default: true

  velioravein.admin:
    description: Administrative permission.
    default: op